@startuml

'
' SPDX-License-Identifier: CC-BY-SA-4.0
'
' Showing the tooling landscape as UML deployement diagram
' This is meant to be a big picture, not listing all details
'

'
' Elements: What is public in the Internet
'

rectangle Public <<Internet>> {

top to bottom direction

node publicsource [
Source Code Repository
----
Public
====
Server
]

node publicartifacts [
Build Artifacts
----
Public
====
Server
]

node publicvulnerabilities [
Security Vulnerabilities
----
Public
====
Server
]

rectangle PublicSoftware <<Master Datata>> {

top to bottom direction


database publicobligtions [
Internal License Obligations
----
Public
====
Database
]

database publiclicenses [
Internal License Master Data 
----
Public
====
Database
]

database publicmetadata [
Internal FOSS Metadata
----
Public
====
Database
]

}

}

'
' Elements: What is inside organisation or comapny
'

rectangle Internal <<Organisation Network>> {

node buildsystem [
Build System
----
Internal
====
Server
]

node internalsource [
Source Code 
----
Internal
====
Server
]

node licensescanning [
License Scanning
----
Internal
====
Server
]

node securityscanning [
Security Scanning
----
Internal
====
Server
]

node internalartifacts [
Build Artifacts
----
Internal
====
Server
]

rectangle InternalSoftware <<Master Datata>> {

database inventory [
Product & Component Inventory
----
Internal
====
Database
]

database ecc [
ECC Metadata
----
Internal
====
Database
]

database licenses [
License Master Data 
----
Internal
====
Database
]

}

}

' 
' relations section
'

publicsource -0)- buildsystem
publicartifacts -0)- buildsystem
internalsource -up0)- buildsystem
licensescanning -up0)- buildsystem
securityscanning -up0)- buildsystem
internalartifacts -up0)- buildsystem
publicvulnerabilities -up0)- securityscanning

' 
' hidden relations to force layout ...
' 

publicsource -[hidden]--> publicartifacts
publicartifacts -[hidden]--> publicvulnerabilities
publicvulnerabilities -[hidden]--> PublicSoftware

publicobligtions -[hidden]--> publiclicenses
publiclicenses -[hidden]--> publicmetadata

buildsystem -[hidden]--> InternalSoftware

inventory -[hidden]--> ecc
ecc -[hidden]--> licenses

@enduml

