@startuml

'
' SPDX-License-Identifier: CC-BY-SA-4.0
'
' Showing the tooling landscape as UML deployement diagram
' This is meant to be a big picture, not listing all details
'

'
' Elements: What is public in the Internet
'

skinparam componentStyle uml2

node "Company External" <<Internet>> {

    component [Source Code Repository] as publicsource <<Public Repository>> 

    component [Artifact Repository] as publicartifacts <<Public Repository>>

    component [Security Vulnerability Database] as publicvulnerabilities <<Public Repository>> 

    node "Public Master Data" {

        component [License Obligations Database] as publicobligations <<Public Repository>> 

        component [Public License Master Database] as publiclicenses <<Public Repository>> 

        component [FOSS Metadata Database] as publicmetadata <<Public Repository>> 

    }

}

'
' Elements: What is inside organisation or comapny
'

node "Company Internal" <<Company Network>> {

    component [Continuous Integration/\nDeployment Infrastructure] as cicd <<Internal Service>>

    component [Build Tool] as buildsystem <<Internal Service>>

    component [Source Code Repository] as internalsource <<Internal Repository>> 

    component [Artifact Repository] as internalartifacts <<Internal Repository>> 

    component [Compliance Checker] as compliancechecker <<Internal Service>>

    component [FOSS Compliance Bundle Generator] as fossbundlegenerator <<Internal Service>>

    component [Component Analysis Service] as componentanalysis <<Internal Service>>

    component [License & Copyright Scanner] as licensescanner <<Internal Service>>

    component [Security Vulnerability Assessment] as securityassessment <<Internal Service>>

    node "Internal Master Data" {

        component [Component Relationship Repository] as componentrelationships <<Internal Repository>>

        component [Component Metadata Repository] as componentmetadata <<Internal Repository>> 

        component [License Metadata Repository] as licenses <<Internal Repository>> 

    }

}

' 
' hidden relations to force layout ...
' 

publicsource -[hidden]-> publicartifacts
publicartifacts -[hidden]-> publicvulnerabilities
publicvulnerabilities -[hidden]-> publicobligations

publicobligations -[hidden]-> publiclicenses
publiclicenses -[hidden]-> publicmetadata

cicd -[hidden]-> internalsource
buildsystem -[hidden]-> internalartifacts
internalsource -[hidden]-> compliancechecker
internalartifacts -[hidden]-> fossbundlegenerator
compliancechecker -[hidden]-> componentanalysis
fossbundlegenerator -[hidden]-> securityassessment
componentanalysis -[hidden]-> licensescanner

componentrelationships -[hidden]-> componentmetadata
componentmetadata -[hidden]-> licenses

@enduml
