@startuml

control "Component\nAnalysis Service" as companalysis
participant "External Source\nCode Repository" as extscm
participant "Artifact Repository" as artifactrepo
participant "FOSS Metadata\nDatabase" as extcomprepo
participant "License &\nCopyright Scanner" as licensescanner
participant "Public License\nMaster Database" as extlicenserepo
participant "License Obligations\nDatabase" as extlicobligrepo
participant "Security Assessment" as secassess
participant "Security Vulnerability\nDatabase" as vuldatabase
participant "Component Metadata\nRepository" as comprepo
participant "License Metadata\nRepository" as licenserepo

companalysis -> extscm : Retrieve source code\nfor new component version
extscm -> companalysis : Component sources
companalysis -> artifactrepo : Store sources for component
companalysis -> extcomprepo : Retrieve known metadata for component
extcomprepo -> companalysis : Known metadata
companalysis -> licensescanner : Scan for license and copyright information
licensescanner -> companalysis : Found license & copyright information
companalysis -> extlicenserepo : Retrieve license information if license unknown
extlicenserepo -> companalysis : License information
companalysis -> extlicobligrepo : Retrieve license obligation information if license unknown
extlicobligrepo -> companalysis : License obligation information
companalysis -> companalysis : Research missing metadata
companalysis -> secassess : Retrieve vulnerability information for component
secassess -> vuldatabase : Get known vulnerabilities\nfor component
vuldatabase -> secassess : Known vulnerabilities
secassess -> companalysis : Known vulnerabilities
companalysis -> companalysis : Final assessment of component
companalysis -> comprepo : Store component assessment and metadata
companalysis -> licenserepo : Update license and obligations information
@enduml
